[versions]
agp = "8.9.3"
kotlin = "2.0.21"
coreKtx = "1.16.0"
junitBomVersion = "5.12.2"
kaspresso = "1.6.0"
appcompat = "1.7.0"
material = "1.12.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }

junit-bom = { module = "org.junit:junit-bom", version.ref = "junitBomVersion"}
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter"}
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher"}

kaspresso = { module = "com.kaspersky.android-components:kaspresso", version.ref = "kaspresso" }

androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

